# Some math with Tensor in Tensorflow

In [1]:
import tensorflow as tf
x = tf.ones(shape = (2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [2]:
x = tf.zeros(shape = (2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [3]:
x = tf.random.normal(shape = (3, 1), mean = 0., stddev = 1.)
print(x)

tf.Tensor(
[[-0.50471175]
 [ 0.6800319 ]
 [ 0.54547876]], shape=(3, 1), dtype=float32)


In [4]:
x = tf.random.uniform(shape = (3, 1), minval = 0., maxval = 1.)
print(x)

tf.Tensor(
[[0.6814643]
 [0.6889249]
 [0.968454 ]], shape=(3, 1), dtype=float32)


The difference between Tensorflow and Numpy is that the Tensor is not assignable while the numpy matrix does

In [5]:
import numpy as np
x = np.ones(shape = (2, 2))
x[0, 0] = 0.
print(x)

[[0. 1.]
 [1. 1.]]


In [6]:
# This thing causes error!!!
# x = tf.ones(shape = (2, 2))
# x[0, 0] = 0.
# print(x)

In [7]:
v = tf.Variable(initial_value = tf.random.normal(shape = (3, 1), mean = 0., stddev = 1.))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.53927   ],
       [0.33573782],
       [0.44044513]], dtype=float32)>


In [8]:
v.assign(tf.ones(shape = (3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [9]:
v[0, 0].assign(3.)
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


In [10]:
v.assign_add(tf.ones(shape = (3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>


In [11]:
a = tf.ones(shape = (2, 2))
b = tf.square(a)
print("b = {}".format(b))
c = tf.sqrt(a)
print("c = {}".format(c))
d = b + c
print("d = {}".format(d))
e = tf.matmul(a, b)
e *= d
print("e = {}".format(e))

b = [[1. 1.]
 [1. 1.]]
c = [[0.99999994 0.99999994]
 [0.99999994 0.99999994]]
d = [[2. 2.]
 [2. 2.]]
e = [[4. 4.]
 [4. 4.]]


### Using the Gradient Tape

In [12]:
input_var = tf.Variable(initial_value = 3.)
with tf.GradientTape() as tape:
    result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


We have seen the case that input of the tape.gradient() function is TF Variable  
Actually it can be any arbitrary TF tensor, however, only trainable tensor can be tracked by default  
To track a constant tensor, we have to mark it as being tracked by calling tape.watch() on it

In [13]:
input_constant = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_constant)
    result = tf.square(input_constant)
gradient = tape.gradient(result, input_constant)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


#### Second-order gradient

In [14]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
    speed = inner_tape.gradient(position, time)
    print("Speed = {}", speed)
acceleration = outer_tape.gradient(speed, time)
print("Acceleration = {}", acceleration)

Speed = {} tf.Tensor(0.0, shape=(), dtype=float32)
Acceleration = {} tf.Tensor(9.8, shape=(), dtype=float32)
